//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPROIZV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Order = new HashSet<Order>();
            this.ServiceandOrder = new HashSet<ServiceandOrder>();
        }
    
        public int ID_Client { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string ForeName { get; set; }
        public int Series { get; set; }
        public int Number { get; set; }
        public System.DateTime DataOfBirthday { get; set; }
        public int Index { get; set; }
        public int ID_City { get; set; }
        public int ID_Street { get; set; }
        public int Home { get; set; }
        public int Flat { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
    
        public virtual City City { get; set; }
        public virtual Street Street { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceandOrder> ServiceandOrder { get; set; }
    }
}
