//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPROIZV
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VinidiktovDEMnovemberEntities : DbContext
    {
        public VinidiktovDEMnovemberEntities()
            : base("name=VinidiktovDEMnovemberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<History_Employee> History_Employee { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Street> Street { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_input> Type_input { get; set; }
        public virtual DbSet<ViewingEmployee> ViewingEmployee { get; set; }
        public virtual DbSet<ViewingOrders> ViewingOrders { get; set; }
        public virtual DbSet<ViewingClient> ViewingClient { get; set; }
        public virtual DbSet<ServiceandOrder> ServiceandOrder { get; set; }
    }
}
