//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPROIZV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.ServiceandOrder = new HashSet<ServiceandOrder>();
        }
    
        public int ID_Order { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public int ID_Client { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public int RentalTime { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Status Status1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceandOrder> ServiceandOrder { get; set; }
    }
}
