//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPROIZV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewingEmployee
    {
        public string Employee { get; set; }
        public string Login { get; set; }
        public int ID_History { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int ID_Employee { get; set; }
        public string Input { get; set; }
    }
}
