//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPROIZV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewingOrders
    {
        public int ID_Client { get; set; }
        public string Client { get; set; }
        public string Service { get; set; }
        public string City { get; set; }
        public System.DateTime DateCreation { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
        public int RentalTime { get; set; }
        public string Status { get; set; }
        public int ID_Street { get; set; }
        public decimal Cost { get; set; }
    }
}
