//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRPROIZV
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewingClient
    {
        public int ID_Client { get; set; }
        public string Client { get; set; }
        public int Series { get; set; }
        public int Number { get; set; }
        public System.DateTime DataOfBirthday { get; set; }
        public int Index { get; set; }
        public string Title { get; set; }
        public string Street { get; set; }
        public int Home { get; set; }
        public int Flat { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
